# Pre-reqs:
#   1)  Install the following as root:    pip install jmespath
#       - doing so allows for use of json_query task

- hosts: onprem-amp
  remote_user: root
  connection: local
  tasks:
      - debug: msg="new project = {{threescale_project}}"

  roles:
    - amp_provision 
    - 3scale_resources
