# Pre-reqs:
#   1)  Install the following as root:    pip install jmespath
#       - doing so allows for use of json_query task

# Purpose
#   - Top level "playbook" that invokes the listed "roles" in sequential order

- hosts: all
  become: false
  connection: local
  tasks:
      - debug: msg="new project = {{threescale_project}}"

  roles:
    - amp_provision 
    - 3scale_resources
