---

- name: Test connection to mysql at {{ apimgmt_db_vm }}
  shell: |
       mysql -h {{apimgmt_db_vm}} -u root -p{{MYSQL_ROOT_PASSWORD}} system_{{db_user}} --execute="select 1"

- name: Test connection to postgresql at {{ apimgmt_db_vm }}
  shell: |
       export PGPASSWORD={{PSQL_USER_PASSWORD}} && \
       psql -h {{apimgmt_db_vm}} -U {{db_user}} zync_production_{{db_user}} -c 'select 1'

- name: Test connection to backend-redis database at {{ apimgmt_db_vm }}
  shell: |
       redis-cli -h {{apimgmt_db_vm}} -a {{ REDIS_PASSWORD }} PING

- name: Test connection to system-redis database using a password at {{ apimgmt_db_vm }}
  shell: |
       redis-cli -h {{apimgmt_db_vm}} -a {{ REDIS_PASSWORD }} PING
  when: SET_REDIS_PASSWORD == true

- name: Test connection to system-redis database without using a password at {{ apimgmt_db_vm }}
  shell: |
       redis-cli -h {{apimgmt_db_vm}} PING
  when: SET_REDIS_PASSWORD == false

# Other potential redis related checks:
#   1) redis-cli -h {{apimgmt_db_vm}} CONFIG GET databases
#   2) redis-cli -h {{apimgmt_db_vm}} INFO keyspace
#   3) redis-cli -h {{apimgmt_db_vm}} INFO | grep ^db
