apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: wf-swarm-oauth
objects:

- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    name: wf-swarm-oauth
  spec:
    tls:
      termination: edge
    to:
      kind: Service
      name: wf-swarm-oauth
      weight: 100
    wildcardPolicy: None

- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: wf-swarm-oauth
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      run: wf-swarm-oauth
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      run: wf-swarm-oauth
    name: wf-swarm-oauth
  spec:
    paused: true
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      run: wf-swarm-oauth
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: wf-swarm-oauth
      spec:
        containers:
        - env:
          - name: JAVA_MAX_MEM_RATIO
            value: "80"
          - name: JAVA_OPTIONS
            value: "${JAVA_OPTIONS}"
          image: docker.io/rhtgptetraining/wf-swarm-oauth:1.0.2
          imagePullPolicy: IfNotPresent
          name: wf-swarm-oauth
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange

parameters:

# If RH-SSO is configured with a cert signed by a legitimate CA (ie:  LetsEncrypt), then a sample value for this param might be :
#    -Djavax.net.debug=ssl -Dswarm.keycloak.json.path=/app/rhsso-config/keycloak.json
#
# If RH-SSO uses a self-signed cert, then a sample value for this param might be:
#    "-Djavax.net.ssl.trustStore=/tmp/realm1_truststore.jks -Djavax.net.ssl.trustStorePassword=changeme -Djavax.net.debug=ssl -Dswarm.keycloak.json.path=/app/rhsso-config/keycloak.json"
- description: JAVA OPTIONS 
  displayName: JAVA_OPTIONS
  name: JAVA_OPTIONS
  required: true
