apiVersion: v1
kind: DeploymentConfig
metadata:
  name: vertx-greeting-service
spec:
  replicas: 0
  selector:
    name: vertx-greeting-service
  strategy:
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        name: vertx-greeting-service
    spec:
      containers:
      - image: ${NEW_VERTX_IMAGE}
        imagePullPolicy: Always
        name: vertx-greeting-service
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
