apiVersion: v1
kind: Template
objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APPLICATION_NAME}-${TAG}
    labels:
      app: ${APPLICATION_NAME}-${TAG}
  spec:
    replicas: 0
    selector:
      app: ${APPLICATION_NAME}-${TAG}
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}-${TAG}
      spec:
        containers:
        - image: CHANGE_ME 
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}-${TAG}
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log

- apiVersion: v1
  kind: Service
  metadata:
    name: ${APPLICATION_NAME}-${TAG}
    labels:
      app: ${APPLICATION_NAME}-${TAG}
    annotations:
      description: The vertx-service http port
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      app: ${APPLICATION_NAME}-${TAG}
      deploymentconfig: ${APPLICATION_NAME}-${TAG}

parameters:
- name: APPLICATION_NAME
  required: true
  value: vertx-greeting
- name: TAG
  required: true
