apiVersion: v1
kind: Template
objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: vertx-greeting-service-${TAG}
  spec:
    replicas: 0
    selector:
      name: vertx-greeting-service-${TAG}
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          name: vertx-greeting-service-${TAG}
      spec:
        containers:
        - image: CHANGE_ME
          imagePullPolicy: Always
          name: vertx-greeting-service-${TAG}
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log

parameters:
- name: TAG
  required: true
