- hosts: apimgmt_db_vm
  remote_user: root
  roles:
    - update
    - tools
    - selinux
    - reboot
    - useradd
    - firewalld
    - yum-clean

    - mariadb
    - postgresql
    - redis

#    - rhn_unsubscribe
