- hosts: apimgmt_db_vm
  become: true
  become_user: root
  tasks:
    - debug: var=ansible_all_ipv4_addresses
    - debug: var=ansible_default_ipv4.address
  roles:
    - update
    - tools
    - selinux
    - reboot
    - firewalld
    - yum-clean

    - mariadb
    - postgresql
    - redis

#    - rhn_unsubscribe
